Add resource_retriever to CATKIN_DEPENDS
This fixes build failure of moveit-ros-planning due to undefined reference to resource_retriever with openembedded.